INSERT INTO UNITY_{{ env }}_DB.PUBLIC.TEST_MIGRATION
(C1, C2)
VALUES
('YASH_DEV_233', 'DEV_YASH_234');


INSERT INTO UNITY_{{ env }}_DB.PUBLIC.TEST_MIGRATION
(C1, C2)
VALUES
('YASH_DEV_332', 'DEV_YASH_321');