USE DATABASE UNITY_{{ env }}_DB;

CREATE OR REPLACE SCHEMA UNITY_{{ env }}_DB.{{schema}} ;

USE SCHEMA UNITY_{{ env }}_DB.{{schema}} ;

CREATE OR REPLACE TABLE TEST_ORDERS
(   "C1" STRING, 
    "C2" STRING
);

INSERT INTO TEST_ORDERS
(C1, C2)
VALUES
('YASH_DEV_2', 'DEV_YASH_2');